[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cascade-sdk"
version = "0.1.0"
description = "A modern, declarative automation library for Python."
requires-python = ">=3.8"
dependencies = [
  "cascade-spec",
  "cascade-engine",
  "cascade-common",
  "cascade-graph",
  "cascade-application"
]

[project.optional-dependencies]
# Providers and their dependencies are now in cascade-library
all = []

[tool.hatch.build.targets.wheel]
packages = ["src/cascade"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
cascade-spec = { workspace = true }
cascade-engine = { workspace = true }
cascade-common = { workspace = true }
cascade-application = { workspace = true }
cascade-graph = { workspace = true }