site_name: Cascade
site_description: 'A modern, declarative automation library for Python.'
repo_url: https://github.com/doucx/Cascade

theme:
  name: material
  language: zh # 设置主题语言为中文
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # 以下是修复 API 参考为空的关键配置
          setup_commands:
            # 强制插件在收集文档前，安装项目本身及其所有可选依赖
            - pip install -e .[all]
          options:
            # (可选, 但推荐) 按源代码中的顺序，而不是字母顺序列出成员
            members_order: source

nav:
  - '首页': 'index.md'
  - '教程':
    - '快速上手': 'tutorial/getting-started.md'
  - '操作指南':
    - '定义计算': 'how-to-guides/defining-computations.md'
    - '使用内置 Provider': 'how-to-guides/using-providers.md'
    - '构建复杂工作流': 'how-to-guides/advanced-workflows.md'
    - '管理资源 (DI)': 'how-to-guides/dependency-injection.md'
    - '提升健壮性': 'how-to-guides/improving-robustness.md'
  - '概念':
    - '核心哲学': 'concepts/philosophy.md'
  - '参考':
    - 'API 参考': 'reference/api.md'
    - 'CLI 工具': 'reference/cli-tools.md'