[project]
name = "cascade-connector-sqlite"
version = "0.1.0"
description = "A zero-dependency SQLite connector for Cascade."
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true