[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cascade-interfaces"
version = "0.1.0"
description = "Protocols and specifications for Cascade."
dependencies = []
requires-python = ">=3.8"

[tool.hatch.build.targets.wheel]
packages = ["src/cascade"]