[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cascade-connector-mqtt"
version = "0.1.0"
description = "An MQTT connector for the Cascade workflow engine."
requires-python = ">=3.8"
dependencies = [
  "cascade-spec",
  "aiomqtt"
]

[tool.hatch.build.targets.wheel]
packages = ["src/cascade"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
cascade-interfaces = { workspace = true }