[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cascade-common"
version = "0.1.0"
description = "Common utilities, protocols, and components for the Cascade ecosystem."
requires-python = ">=3.8"

[tool.hatch.build.targets.wheel]
packages = ["src/cascade"]